config/routes.rb
Longlivesnarf::Application.routes.draw do
  resources :snarves

end

app/models/snarf.rb
class Snarf < ActiveRecord::Base
  attr_accessible :quote
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/snarves_controller.rb
class SnarvesController < ApplicationController
  # GET /snarves
  # GET /snarves.json
  def index
    @snarves = Snarf.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @snarves }
    end
  end

  # GET /snarves/1
  # GET /snarves/1.json
  def show
    @snarf = Snarf.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @snarf }
    end
  end

  # GET /snarves/new
  # GET /snarves/new.json
  def new
    @snarf = Snarf.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @snarf }
    end
  end

  # GET /snarves/1/edit
  def edit
    @snarf = Snarf.find(params[:id])
  end

  # POST /snarves
  # POST /snarves.json
  def create
    @snarf = Snarf.new(params[:snarf])

    respond_to do |format|
      if @snarf.save
        format.html { redirect_to @snarf, notice: 'Snarf was successfully created.' }
        format.json { render json: @snarf, status: :created, location: @snarf }
      else
        format.html { render action: "new" }
        format.json { render json: @snarf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /snarves/1
  # PUT /snarves/1.json
  def update
    @snarf = Snarf.find(params[:id])

    respond_to do |format|
      if @snarf.update_attributes(params[:snarf])
        format.html { redirect_to @snarf, notice: 'Snarf was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @snarf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snarves/1
  # DELETE /snarves/1.json
  def destroy
    @snarf = Snarf.find(params[:id])
    @snarf.destroy

    respond_to do |format|
      format.html { redirect_to snarves_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snarves_helper.rb
module SnarvesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Longlivesnarf</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/snarves/_form.html.erb
<%= form_for(@snarf) do |f| %>
  <% if @snarf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snarf.errors.count, "error") %> prohibited this snarf from being saved:</h2>

      <ul>
      <% @snarf.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br />
    <%= f.text_field :quote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snarves/edit.html.erb
<h1>Editing snarf</h1>

<%= render 'form' %>

<%= link_to 'Show', @snarf %> |
<%= link_to 'Back', snarves_path %>

app/views/snarves/index.html.erb
<h1>Listing snarves</h1>

<table>
  <tr>
    <th>Quote</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snarves.each do |snarf| %>
  <tr>
    <td><%= snarf.quote %></td>
    <td><%= link_to 'Show', snarf %></td>
    <td><%= link_to 'Edit', edit_snarf_path(snarf) %></td>
    <td><%= link_to 'Destroy', snarf, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snarf', new_snarf_path %>

app/views/snarves/new.html.erb
<h1>New snarf</h1>

<%= render 'form' %>

<%= link_to 'Back', snarves_path %>

app/views/snarves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quote:</b>
  <%= @snarf.quote %>
</p>


<%= link_to 'Edit', edit_snarf_path(@snarf) %> |
<%= link_to 'Back', snarves_path %>